configs_forwarding_options:
  - set forwarding-options sampling instance s1 input rate 10
  - set forwarding-options sampling instance s1 family inet output flow-server 172.20.232.134 port 9995
  - set forwarding-options sampling instance s1 family inet output flow-server 172.20.232.134 autonomous-system-type origin
  - set forwarding-options sampling instance s1 family inet output flow-server 172.20.232.134 version-ipfix template ipv4
  - set forwarding-options sampling instance s1 family inet output flow-server 208.76.14.247 port 20013
  - set forwarding-options sampling instance s1 family inet output flow-server 208.76.14.247 autonomous-system-type origin