base_chassis_configuration_context: 
  - set chassis aggregated-devices ethernet device-count 10
  - set chassis fpc 0 pic 0 tunnel-services bandwidth 10g
  - set chassis fpc 0 pic 0 port 0 speed 100g
  - set chassis fpc 0 pic 0 port 1 speed 100g
  - set chassis fpc 0 pic 0 port 2 speed 10g
  - set chassis fpc 0 pic 0 port 3 speed 10g
  - set chassis fpc 0 pic 1 port 0 speed 10g
  - set chassis fpc 0 pic 1 port 1 speed 10g
  - set chassis fpc 0 pic 1 port 2 speed 10g
  - set chassis fpc 0 pic 1 port 3 speed 10g
  - set chassis fpc 0 pic 1 port 4 speed 10g
  - set chassis fpc 0 pic 1 port 5 speed 10g
  - set chassis fpc 0 pic 1 port 6 speed 10g
  - set chassis fpc 0 pic 1 port 7 speed 10g
  - set chassis fpc 0 sampling-instance s1
  - set chassis fpc 0 inline-services flow-table-size ipv4-flow-table-size 15
  - set chassis network-services enhanced-ip
  - set services flow-monitoring version-ipfix template ipv4 flow-active-timeout 60
  - set services flow-monitoring version-ipfix template ipv4 flow-inactive-timeout 70
  - set services flow-monitoring version-ipfix template ipv4 template-refresh-rate packets 30
  - set services flow-monitoring version-ipfix template ipv4 template-refresh-rate seconds 60
  - set services flow-monitoring version-ipfix template ipv4 option-refresh-rate packets 30
  - set services flow-monitoring version-ipfix template ipv4 option-refresh-rate seconds 30
  - set services flow-monitoring version-ipfix template ipv4 ipv4-template